Editar
Jmiguel14/meet-goal-project pull request #36
Opened 2021-07-05 16:26 UTC by FreddyJR1995

Se establece la lectura en tiempo real de la base al momento de editar cualquier apartado del perfil del jugador.
Se corrigen algunos errores ortográficos.

2021-07-05 17:35 UTC, Jmiguel14 commented
Corregir los siguientes errores:
1. error de lectura de datos _undefined_
![image](https://user-images.githubusercontent.com/56648593/124502840-db092600-dd89-11eb-9baa-6ea4dbb29c24.png)
2. Realizar las validaciones de datos para todos los formularios, ya que no esta validando cuando se guarda el formulario con datos vacíos.
3. Colocar el nombre de usuario en el header cuando entra al perfil.
4. Mostrar en canales solo el ícono de la red social con una redirección respectiva.

2021-07-07 02:00 UTC, Jmiguel14 requested changes
Algunos errores y mejoras que se deben hacer:
1. Usar una etiqueta `<form>` o usar el hook `useForm` para controlar los resets de los formularios, ya que esta dando errores cuando se esta utilizando la función reset del evento (e.target.reset()). El error es causado porque se esta utilizando un evento de un botón en vez del evento del formulario.
2. Cambiar los tipados de `any` a el correcto tipado.
3. Cambiar el color del toast (de clase "primary" a 'success') cuando se edita una información con éxito.
4. Cambiar diseño del segmento de DATOS PSICOLÓGICOS en el apartado de personalidad debido a que no se da a entender la personalidad para otros usuarios.
5. Cambiar la url del **backButton** del perfil, ya que este esta redirigiendo a una página errónea cuando se abren mas formularios de edición.
6. Borrar los `console.logs`

2021-07-07 02:00 UTC, Jmiguel14 commented on src/firebase/client.tsx
> +    console.log("Registro actualizado");
Utilizar el hook `useIonToast` para mostrar los mensajes.

2021-07-08 15:38 UTC, Jmiguel14 reviewed
Se registra el siguiente error cuando se guardar información vacía en un formulario, en este caso para los formularios de datos psicológicos y médicos.
![image](https://user-images.githubusercontent.com/56648593/124950813-5f50e880-dfd8-11eb-8ecb-4cfb17d1e2b1.png)

2021-07-11 21:16 UTC, Jmiguel14 requested changes
Como cambios generales se deben, borrar importaciones o código que no se este utilizando y pasar al ingles variables que se estén utilizando en español.

2021-07-11 21:16 UTC, Jmiguel14 commented on src/components/PlayerInfo/PlayerInfo.tsx
Cambiar el uso de history por un `IonRouterLink ` aquí y todas las demás partes que se este utilizando la misma lógica. Esto es para que el código sea más leíble.

2021-07-11 21:16 UTC, Jmiguel14 commented on src/components/PlayerInfo/AvatarPlayer/AvatarPlayer.tsx
>              <IonAvatar className="avatar">
Para utilizar el Avatar se puede utilizar el componente `Avatar` creado en la carpeta de los componentes. Esto es para reutilizar componentes y reducir el código.

2021-07-11 21:16 UTC, Jmiguel14 commented on src/pages/UpdatePhotos/UpdatePhotos.tsx
> +  }
Utilizar el tipo de evento correspondiente en la función.

2021-07-11 21:16 UTC, Jmiguel14 commented on src/contexts/AuthContext.tsx
>        }
Estas funciones deben ir dentro del try, esto es necesario, ya que si se da un error en la funciones la aplicación no se rompería por completo.

2021-07-12 02:57 UTC, FreddyJR1995 commented on src/components/PlayerInfo/AvatarPlayer/AvatarPlayer.tsx
>              <IonAvatar className="avatar">
Para esta parte, se evita el uso del componente Avatar por cuestiones de estilos y la superposición de esta a la portada

2021-07-12 02:58 UTC, FreddyJR1995 commented on src/pages/UpdatePhotos/UpdatePhotos.tsx
> +  }
El tipo dado interfiere con la funcionalidad de la propiedad target.files del evento es por eso que se lo determina como any.

2021-07-13 01:06 UTC, Jmiguel14 requested changes
Solicitud de cambios.

2021-07-13 01:06 UTC, Jmiguel14 commented on src/pages/UpdatePhotos/UpdatePhotos.tsx
> +  }, [task]);
- Cambiar el doble igual por el triple igual, esto debido a que el primer igual solo verifica el valor a diferencia del triple que  verifica el tipo de valor también.
- Añadir constantes para los strings siempre que se pueda, por ejemplo en el `typePhoto` se podría crear un objeto con los datos y luego llamarlos donde sean requeridos. En este caso este objeto pude ser colocado en el componente que se esta usando siempre y cuando no sea reutilizado en otros componentes. Dado este caso se debería crear la constante dentro de la carpeta `constants`.
- Debido a que las colecciones también son strings, y están siendo reutilizados en otros componentes se requiere que se cree una objeto que contenga las constantes o nombres de cada una de las colecciones.

2021-07-13 03:36 UTC, Jmiguel14 approved these changes

2021-07-13 03:37 UTC, merged