15 crear convocatorias
Jmiguel14/meet-goal-project pull request #46
Opened 2021-07-15 23:19 UTC by FreddyJR1995

Se implementan las siguientes actividades:
- Página para crear convocatorias.
- Página para visualizar el listado de convocatorias creada por el club.
- Función para el registro a la base de datos.
- Función para la lectura de las convocatorias que creo el usuario que inicio sesión.

2021-07-18 17:07 UTC, FreddyJR1995 commented
Se agrego la visualización del detalle de una convocatoria por parte del club, para esto se creo una ruta dinámica que contenga el id de la convocatoria y cargar los datos.

2021-07-18 21:40 UTC, Jmiguel14 requested changes

2021-07-18 21:40 UTC, Jmiguel14 commented on src/firebase/client.tsx
> +}
Añadir el campo `createdAt` en e registro de la convocatoria. Si es posible cambiar el nombre de la función de `AddNewCallClub` a `addNewClubCall`, ya que el nombre de las funciones que no son componentes deben empezar con minúscula.

2021-07-18 21:40 UTC, Jmiguel14 commented on src/firebase/client.tsx
> +};
Cambiar el nombre semántico de la función de `getMyCallsData` a `getCalls `o `getCallsData`. Además, cambiar el orderBy de "endDate" por "createdAt".

2021-07-18 21:40 UTC, Jmiguel14 commented on src/pages/CallDetails/CallDetails.tsx
> +  }, [callData]);
Utilizar a lógica que se encuentra dentro de los efectos en un nuevo fichero dentro de la carpeta del servicio de **firebase**.

2021-07-18 21:40 UTC, Jmiguel14 commented on src/pages/CallDetails/CallDetails.tsx
> +            </IonButton>
Utilizar la prop `routerLink` del `IonButton` para hacer la redirección, de esta manera se evita utilizar el `useHistory`. Los mismo se puede hacer en otros bótones.

2021-07-18 21:40 UTC, Jmiguel14 commented on src/pages/CallsListClub/CallsListClub.tsx
> +  }, []);
Utilizar el unsubscribe, sólo se debe descomentar la línea del return.

2021-07-18 21:40 UTC, Jmiguel14 commented on src/pages/CallsListClub/CallsListClub.tsx
> +  }
Pasar esta función a un nuevo fichero. Para esto se debe:
1. Crear una carpeta llamada `utils` la cual va a contener a la carpeta de **firebase** y un archivo de esta función de conversión de fecha.

2021-07-19 16:32 UTC, Jmiguel14 commented
No se está borrando la información ingresada en el formulario de crear una convocatoria.

2021-07-19 21:25 UTC, Jmiguel14 commented
La descripción no esta siendo limpiada como los demás inputs y el error de campo requerido permanece después de ingresar de nuevo la fecha de inicio y fin.
![Uploading image.png…]()

2021-07-20 01:03 UTC, Jmiguel14 approved these changes

2021-07-20 01:03 UTC, merged