22 notificar seleccion
Jmiguel14/meet-goal-project pull request #70
Opened 2021-08-01 17:22 UTC by FreddyJR1995

Se implementa:
- El **cuadro de dialogo y el botón para notificar** la selección a los jugadores del parte del club.
-  El registro a la base de datos de los detalles de la notificación.
- La **visualización de las notificaciones** para el usuario que inicie sesión.
- Se controla que se muestren solo las **notificaciones que aun no han sido leídas**.
- Se trata de controlar que el **IonBadge se pinte en el icono de notificaciones** cuando estas no estén leídas.
- Se agrega el campo **isClosed** a la convocatoria esta para que no sea visible a los clubes después de cerrarlas.
** Existe un problema con el ionBadge al momento de ir actualizando el estado de la notificación ya que el Tabroot no se rerenderiza en los cambios**

2021-08-01 22:29 UTC, Jmiguel14 requested changes
Para el tema del `badge`, se podría crear una un enlance en la notificación que lo lleve a la convocatoria que fue aceptado,  de esta manera se podría establecer el valor del flag a false de nuevo. O también se podría establecer ese valor cada vez que cambie de tab.
Por otro lado, la convocatoria tal vez no debería eliminarse sino solo cambiar en la fecha de **"Termina en"** a poner cerrada o algo parecido. Esto es para que el club pueda ser capaz de volver a revisar a los jugadores de la convocatoria.

2021-08-01 22:29 UTC, Jmiguel14 commented on src/constants/notificationsTitles.js
> +  PLAYERACCEPT: "Haz sido seleccionado en una convocatoria",
Cambiar PLAYERACCEPT por PLAYERACCEPTED

2021-08-01 22:29 UTC, Jmiguel14 commented on src/utils/converterDate.tsx
> +}
Cambiar la semantica de la función. Especialmente por el resultado de la función, en este caso podría ser algo como `isCallClosed` o algo parecido. El actualDate también podría cambiar a `currentDate`.

2021-08-02 04:23 UTC, FreddyJR1995 commented
Se corrigen los detalles notificados ha modificar , además se integra un modal para los detalles de una notificación y seteo del estado de la misma. Sin embargo, aun existe inconvenientes con el IonBadge.

2021-08-03 00:44 UTC, Jmiguel14 requested changes

2021-08-03 00:44 UTC, Jmiguel14 commented on src/firebase/notificationsServices.tsx
>    });
Cambiar el atributo `name` por `clubName`

2021-08-03 00:44 UTC, Jmiguel14 commented on src/pages/Notifications/Notifications.tsx
> +                      : ""}
Cambiar de el "por el" a "por el club".

2021-08-03 00:45 UTC, Jmiguel14 approved these changes

2021-08-03 02:42 UTC, merged